#!/usr/bin/env bash
# A Bash that configures a brand new Ubuntu machine.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "15i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
