#!/usr/bin/env bash
#Tells the story of passwd

while IFS=':' read -r username password user_id grp_id info home_dir cmd_shell; do
  echo "The user $username is part of the $grp_id gang,"\
  "lives in $home_dir and rides $cmd_shell."\
  "$user_id's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
