#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 20 using while loop

kui=1

while [ $kui -le 20 ]
do
 echo "$kui"
 case $kui in
  "4") echo "bad luck from China";;
  "9") echo "bad luck from Japan";;
  "17") echo "bad luck from Italy";;
 esac
 (( kui++ ))
done
