#!/usr/bin/env bash
#A Bash script that displays the time for 12 hours and 59 minutes
kui=0
while ((kui <= 12)); do
	echo "Hour: $kui"
	nzi=1
	while ((nzi <= 59)); do
		echo $nzi
		((nzi+=1))
	done
	((kui+=1))
done
